services:
  restaurant-catalog-api:
    build:
      context: ../../../..
      dockerfile: apps/restaurant-catalog-api/Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ../../../../apps/restaurant-catalog-api/.env.local
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    shm_size: 128mb # shared memory limit
    ports:
      - 5432:5432
    env_file:
      - ../../../../apps/restaurant-catalog-api/.env.local
