FROM node:24-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable
COPY . /workspace
WORKDIR /workspace

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpx nx build haru-cafe-website

FROM nginx:1.29-alpine
COPY systems/restaurant-catalog/envs/dev/nginx/haru-cafe-website.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/apps/haru-cafe-website/dist/haru-cafe/browser/ /var/www/haru-cafe/browser/

EXPOSE 80
