openapi: 3.0.3
info:
  title: Haru Cafe's API
  version: 1.0.0
paths:
  /api/cms/menu-item-categories/:
    get:
      operationId: api_cms_menu_item_categories_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItemCategory'
          description: ''
    post:
      operationId: api_cms_menu_item_categories_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemCategory'
          description: ''
  /api/cms/menu-item-categories/{id}/:
    get:
      operationId: api_cms_menu_item_categories_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item category.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemCategory'
          description: ''
    put:
      operationId: api_cms_menu_item_categories_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item category.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItemCategory'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemCategory'
          description: ''
    patch:
      operationId: api_cms_menu_item_categories_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item category.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemCategory'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemCategory'
          description: ''
    delete:
      operationId: api_cms_menu_item_categories_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item category.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/cms/menu-item-sizes/:
    get:
      operationId: api_cms_menu_item_sizes_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItemSize'
          description: ''
    post:
      operationId: api_cms_menu_item_sizes_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemSize'
          description: ''
  /api/cms/menu-item-sizes/{id}/:
    get:
      operationId: api_cms_menu_item_sizes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item size.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemSize'
          description: ''
    put:
      operationId: api_cms_menu_item_sizes_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item size.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItemSize'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemSize'
          description: ''
    patch:
      operationId: api_cms_menu_item_sizes_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item size.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemSize'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemSize'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMenuItemSize'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItemSize'
          description: ''
    delete:
      operationId: api_cms_menu_item_sizes_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item size.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/cms/menu-items/:
    get:
      operationId: api_cms_menu_items_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MenuItem'
          description: ''
    post:
      operationId: api_cms_menu_items_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItem'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
  /api/cms/menu-items/{id}/:
    get:
      operationId: api_cms_menu_items_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    put:
      operationId: api_cms_menu_items_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MenuItem'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    patch:
      operationId: api_cms_menu_items_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMenuItem'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MenuItem'
          description: ''
    delete:
      operationId: api_cms_menu_items_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this menu item.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/debug/auth/ping/:
    get:
      operationId: api_debug_auth_ping_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/debug/ping/:
    get:
      operationId: api_debug_ping_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/seed/seed_image_urls/:
    get:
      operationId: api_seed_seed_image_urls_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/seed/seed_menu_item_json/:
    get:
      operationId: api_seed_seed_menu_item_json_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    MenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 256
        image:
          type: string
          format: uri
          nullable: true
        description:
          type: string
          nullable: true
          maxLength: 1024
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        categories:
          type: array
          items:
            type: integer
        isFavorite:
          type: boolean
        isActive:
          type: boolean
        size:
          type: integer
          nullable: true
      required:
      - categories
      - id
      - name
      - price
    MenuItemCategory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          nullable: true
          maxLength: 256
      required:
      - id
    MenuItemSize:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        size:
          type: string
          nullable: true
          maxLength: 256
      required:
      - id
    PatchedMenuItem:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 256
        image:
          type: string
          format: uri
          nullable: true
        description:
          type: string
          nullable: true
          maxLength: 1024
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        categories:
          type: array
          items:
            type: integer
        isFavorite:
          type: boolean
        isActive:
          type: boolean
        size:
          type: integer
          nullable: true
    PatchedMenuItemCategory:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          nullable: true
          maxLength: 256
    PatchedMenuItemSize:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        size:
          type: string
          nullable: true
          maxLength: 256
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
servers:
- url: http://localhost:8000
- url: http://host.docker.internal:8000
